name: S3 Deployment with parameter

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Enter environment
        required: true
        options:
        - dev
        - prod
        - stage

jobs:
  s3_deploy:
    runs-on: self-hosted

    steps:
      - name: Displaying Environment
        run: echo "${{inputs.environment}}"
        
      - name: Create S3 bucket
        run: |
          aws s3 mb hex-s3-gh-${{ inputs.environment }}
          if [ "${{ inputs.environment }}" == 'prod' ]; then
            aws s3api put-bucket-versioning --bucket hex-s3-gh-${{ inputs.environment }} --versioning-configuration Status=Enabled
          fi
        continue-on-error: true
			
      - name: Upload files to s3
        run: aws s3 cp upload/ s3://hex-s3-gh-${{ inputs.environment }}/upload/ --recursive