name: S3 Deployment with parameter

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Enter environment
        required: true
        options:
        - dev
        - prod
        - stage

jobs:
  s3_deploy:
    runs-on: self-hosted

    steps:
      - name: Displaying Environment
        run: echo "${{inputs.environment}}"